name: ${project.pluginName}
version: ${project.version}
author: magicmq
main: dev.magicmq.pyspigot.bukkit.loader.BukkitLoader
load: STARTUP
api-version: '1.13'
softdepend: [ProtocolLib, PlaceholderAPI, PacketEvents]
commands:
  pyspigot:
    description: The main command for PySpigot.
    aliases: [ps]