# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Copy artifacts to staging directory
        run: mkdir staging && find . -type f -path "*/target/*.jar" -exec rsync -a {} staging/ \;
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyspigot-build-${{ github.run_number }}
          path: ./staging/*.jar
          overwrite: true